// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltbxtjdpsooedpbkmmhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0Ynh0amRwc29vZWRwYmttbWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjI2MTAsImV4cCI6MjA3MjM5ODYxMH0.taca3gSSDQb8O6QSti2piQmq56PcJF5Tn0KrSYDkqHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});